version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJAN17Sept1Project
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.mjan17sept1.integrations:DafTest
  packages:
  - name: MJAN17Sept1Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
- serviceName: GB_1:readGlobalvariable
  packages:
  - name: DADA_GlobalVariable1
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
